### ISSUE TITLE
[Install guide improve]

### ISSUE THREAD

**Issue by jolet** [jaeg/NodeWrecker#2]
Hi, please update installation guide for helm install linux x86, instructions unclear was stuck when installing on linux x86
git clone https://github.com/jaeg/NodeWrecker.git && cd NodeWrecker
helm upgrade --install pi-wrecker ./helm-chart/

kubectl get pod status
pi-wrecker-helm-chart-764cfd9d64-kbzpw                            0/1     CrashLoopBackOff   2          41s

kubectl logs pi-wrecker-helm-chart-764cfd9d64-kbzpw 
standard_init_linux.go:211: exec user process caused "exec format error"

Found later this was due to installing wrong version intended for pi, for linux x86 architecture install it was required to
edit helm-chart/Chart.yaml
change line 
appVersion: latest-pi 
with 
appVersion: latest

then install as 
helm upgrade --install wrecker ./helm-chart/

**Comment by jaeg** [comment]
Hello, I've updated the chart.yaml to make the default "latest" so that the instructions will by default work with Linux x86.  I created a new step for making it run on a Pi.

I apologize for any confusion, the charts and readme for those sections should of been defaulted to linux x86 with the Pi being a bonus feature.  It was an oversight on my part.
